export const ErrorCodes = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTEHNTICATED: 'UNAUTEHNTICATED',
  NOT_FOUND: 'NOT_FOUND',
  NETWORK_ERROR: 'NETWORK_ERROR',
}

export const ErrorMessages = {
  [ErrorCodes.INVALID_REQUEST]: 'INVALID_REQUEST',
  [ErrorCodes.UNKNOWN_ERROR]: 'UNKNOWN_ERROR',
  [ErrorCodes.FORBIDDEN]: 'FORBIDDEN',
  [ErrorCodes.UNAUTEHNTICATED]: 'UNAUTEHNTICATED',
  [ErrorCodes.NOT_FOUND]: 'NOT_FOUND',
  [ErrorCodes.NETWORK_ERROR]: 'NETWORK_ERROR',
}
